In [9]:
# Cell 1 — Load and inspect
import pandas as pd
df = pd.read_parquet("../data/raw/qualifying_laps_raw.parquet")
print(df.shape)
df.head()

(37238, 41)

,Time,Driver,DriverNumber,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,...,Year,RoundNumber,EventName,Country,CircuitShortName,TrackTemp,AirTemp,Humidity,WindSpeed,Rainfall
0,0 days 00:24:04.661000,VER,33,NaT,1.0,1.0,0 days 00:21:18.434000,NaT,NaT,0 days 00:01:24.332000,...,2021,1,Bahrain Grand Prix,Bahrain,Sakhir,33.84359,29.060256,46.544872,0.966667,False
1,0 days 00:25:35.160000,VER,33,0 days 00:01:30.499000,2.0,1.0,NaT,NaT,0 days 00:00:28.807000,0 days 00:00:38.980000,...,2021,1,Bahrain Grand Prix,Bahrain,Sakhir,33.84359,29.060256,46.544872,0.966667,False
2,0 days 00:27:25.520000,VER,33,0 days 00:01:50.360000,3.0,1.0,NaT,0 days 00:27:23.844000,0 days 00:00:34.462000,0 days 00:00:43.825000,...,2021,1,Bahrain Grand Prix,Bahrain,Sakhir,33.84359,29.060256,46.544872,0.966667,False
3,0 days 00:44:22.361000,VER,33,NaT,4.0,2.0,0 days 00:42:21.384000,NaT,NaT,0 days 00:00:54.163000,...,2021,1,Bahrain Grand Prix,Bahrain,Sakhir,33.84359,29.060256,46.544872,0.966667,False
4,0 days 00:45:52.679000,VER,33,0 days 00:01:30.318000,5.0,2.0,NaT,NaT,0 days 00:00:28.964000,0 days 00:00:38.858000,...,2021,1,Bahrain Grand Prix,Bahrain,Sakhir,33.84359,29.060256,46.544872,0.966667,False

In [10]:
# Cell 2 — Check coverage
print("Seasons:", sorted(df["Year"].unique()))
print("Circuits:", df["EventName"].nunique())
print("Drivers:", df["Driver"].nunique())

Seasons: [2021, 2022, 2023, 2024, 2025, 2026]
Circuits: 29
Drivers: 36

In [11]:
# Cell 3 — Check weather columns
df[["TrackTemp", "AirTemp", "Humidity", "WindSpeed", "Rainfall"]].describe()

          TrackTemp       AirTemp      Humidity     WindSpeed
count  37238.000000  37238.000000  37238.000000  37238.000000
mean      33.966671     23.244333     55.530186      1.586727
std        9.954975      5.579768     19.065954      0.961438
min       12.549412     11.728235     12.531646      0.197436
25%       26.710526     19.001010     39.387500      0.806173
50%       34.152727     24.188000     57.114943      1.459524
75%       41.015385     27.023750     69.712329      2.174359
max       59.239080     35.460759     93.580247      5.006329

In [12]:
# Cell 4 — Check for nulls
df.isnull().sum().sort_values(ascending=False).head(15)

Deleted               37238
Position              37238
LapStartDate          37238
PitInTime             26536
PitOutTime            26437
LapTime               11992
SpeedFL               10700
Sector1SessionTime     9039
Sector1Time            9036
Sector3Time            2607
Sector3SessionTime     2607
SpeedST                2239
SpeedI2                 622
Sector2Time             615
Sector2SessionTime      615
dtype: int64